In [1]:
import pandas as pd

data = pd.read_csv("../data/sales.csv")
data.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer

In [29]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 28 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   date                     73100 non-null  datetime64[us]
 1   store_id                 73100 non-null  str
 2   product_id               73100 non-null  str
 3   inventory_level          73100 non-null  int64
 4   units_sold               73100 non-null  int64
 5   units_ordered            73100 non-null  int64
 6   demand_forecast          73100 non-null  float64
 7   price                    73100 non-null  float64
 8   discount                 73100 non-null  int64
 9   competitor_pricing       73100 non-null  float64
 10  day                      73100 non-null  int32
 11  month                    73100 non-null  int32
 12  year                     73100 non-null  int32
 13  day_of_week              73100 non-null  int32
 14  category_Electronics     73100 non-null  bool
 15  category_Furniture       73100 non-null  bool
 16  category_Groceries       73100 non-null  bool
 17  category_Toys            73100 non-null  bool
 18  region_North             73100 non-null  bool
 19  region_South             73100 non-null  bool
 20  region_West              73100 non-null  bool
 21  weather_condition_Rainy  73100 non-null  bool
 22  weather_condition_Snowy  73100 non-null  bool
 23  weather_condition_Sunny  73100 non-null  bool
 24  seasonality_Spring       73100 non-null  bool
 25  seasonality_Summer       73100 non-null  bool
 26  seasonality_Winter       73100 non-null  bool
 27  holiday_promotion        0 non-null      float64
dtypes: bool(13), datetime64[us](1), float64(4), int32(4), int64(4), str(2)
memory usage: 8.2 MB

In [4]:
data.describe()

,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Holiday/Promotion,Competitor Pricing
count,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000
mean,274.469877,136.464870,110.004473,141.494720,55.135108,10.009508,0.497305,55.146077
std,129.949514,108.919406,52.277448,109.254076,26.021945,7.083746,0.499996,26.191408
min,50.000000,0.000000,20.000000,-9.990000,10.000000,0.000000,0.000000,5.030000
25%,162.000000,49.000000,65.000000,53.670000,32.650000,5.000000,0.000000,32.680000
50%,273.000000,107.000000,110.000000,113.015000,55.050000,10.000000,0.000000,55.010000
75%,387.000000,203.000000,155.000000,208.052500,77.860000,15.000000,1.000000,77.820000
max,500.000000,499.000000,200.000000,518.550000,100.000000,20.000000,1.000000,104.940000

In [5]:
data.isnull().sum()

Date                  0
Store ID              0
Product ID            0
Category              0
Region                0
Inventory Level       0
Units Sold            0
Units Ordered         0
Demand Forecast       0
Price                 0
Discount              0
Weather Condition     0
Holiday/Promotion     0
Competitor Pricing    0
Seasonality           0
dtype: int64

In [6]:
data.columns = data.columns.str.lower().str.replace(" ", "_")

In [7]:
print(data['store_id'].nunique())
print(data['product_id'].nunique())

5
20

In [20]:
data['date'] = pd.to_datetime(data['date'])

In [21]:
data.isnull().sum()

date                           0
store_id                       0
product_id                     0
inventory_level                0
units_sold                     0
units_ordered                  0
demand_forecast                0
price                          0
discount                       0
competitor_pricing             0
day                            0
month                          0
year                           0
day_of_week                    0
category_Electronics           0
category_Furniture             0
category_Groceries             0
category_Toys                  0
region_North                   0
region_South                   0
region_West                    0
weather_condition_Rainy        0
weather_condition_Snowy        0
weather_condition_Sunny        0
seasonality_Spring             0
seasonality_Summer             0
seasonality_Winter             0
holiday_promotion          73100
dtype: int64

In [22]:
data['units_sold'] = data['units_sold'].fillna(data['units_sold'].mean())
data['price'] = data['price'].fillna(data['price'].mean())

In [23]:
data['weather_condition'] = data['weather_condition'].fillna("Unknown")

KeyError: 'weather_condition'

In [12]:
data = data.drop_duplicates()

In [13]:
data['day'] = data['date'].dt.day
data['month'] = data['date'].dt.month
data['year'] = data['date'].dt.year
data['day_of_week'] = data['date'].dt.dayofweek

In [ ]:
data = pd.get_dummies(data, columns=[
    'category',
    'region',
    'weather_condition',
    'seasonality'
], drop_first=True)

KeyError: "None of [Index(['category', 'region', 'seasonality'], dtype='str')] are in the [columns]"

In [16]:
print(data['holiday/promotion'].unique())

[0 1]

In [17]:
data['holiday_promotion'] = data['holiday/promotion'].map({
    'Yes': 1,
    'No': 0
})

In [18]:
data = data.drop('holiday/promotion', axis=1)

In [19]:
data.head()

,date,store_id,product_id,inventory_level,units_sold,units_ordered,demand_forecast,price,discount,competitor_pricing,...,region_North,region_South,region_West,weather_condition_Rainy,weather_condition_Snowy,weather_condition_Sunny,seasonality_Spring,seasonality_Summer,seasonality_Winter,holiday_promotion
0,2022-01-01,S001,P0001,231,127,55,135.47,33.50,20,29.69,...,True,False,False,True,False,False,False,False,False,NaN
1,2022-01-01,S001,P0002,204,150,66,144.04,63.01,20,66.16,...,False,True,False,False,False,True,False,False,False,NaN
2,2022-01-01,S001,P0003,102,65,51,74.02,27.99,10,31.32,...,False,False,True,False,False,True,False,True,False,NaN
3,2022-01-01,S001,P0004,469,61,164,62.18,32.72,10,34.74,...,True,False,False,False,False,False,False,False,False,NaN
4,2022-01-01,S001,P0005,166,14,135,9.26,73.64,0,68.95,...,False,False,False,False,False,True,False,True,False,NaN

In [18]:
X = data.drop(['units_sold', 'date'], axis=1)
y = data['units_sold']

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [20]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=100, max_depth=10)

model.fit(X_train, y_train)

ValueError: could not convert string to float: 'S002'