In [1]:
import pandas as pd

data = pd.read_csv("../data/sales.csv")
data.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer

In [2]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                73100 non-null  str
 1   Store ID            73100 non-null  str
 2   Product ID          73100 non-null  str
 3   Category            73100 non-null  str
 4   Region              73100 non-null  str
 5   Inventory Level     73100 non-null  int64
 6   Units Sold          73100 non-null  int64
 7   Units Ordered       73100 non-null  int64
 8   Demand Forecast     73100 non-null  float64
 9   Price               73100 non-null  float64
 10  Discount            73100 non-null  int64
 11  Weather Condition   73100 non-null  str
 12  Holiday/Promotion   73100 non-null  int64
 13  Competitor Pricing  73100 non-null  float64
 14  Seasonality         73100 non-null  str
dtypes: float64(3), int64(5), str(7)
memory usage: 8.4 MB

In [3]:
data.describe()

,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Holiday/Promotion,Competitor Pricing
count,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000
mean,274.469877,136.464870,110.004473,141.494720,55.135108,10.009508,0.497305,55.146077
std,129.949514,108.919406,52.277448,109.254076,26.021945,7.083746,0.499996,26.191408
min,50.000000,0.000000,20.000000,-9.990000,10.000000,0.000000,0.000000,5.030000
25%,162.000000,49.000000,65.000000,53.670000,32.650000,5.000000,0.000000,32.680000
50%,273.000000,107.000000,110.000000,113.015000,55.050000,10.000000,0.000000,55.010000
75%,387.000000,203.000000,155.000000,208.052500,77.860000,15.000000,1.000000,77.820000
max,500.000000,499.000000,200.000000,518.550000,100.000000,20.000000,1.000000,104.940000

In [4]:
data.isnull().sum()

Date                  0
Store ID              0
Product ID            0
Category              0
Region                0
Inventory Level       0
Units Sold            0
Units Ordered         0
Demand Forecast       0
Price                 0
Discount              0
Weather Condition     0
Holiday/Promotion     0
Competitor Pricing    0
Seasonality           0
dtype: int64

In [5]:
data.columns = data.columns.str.lower().str.replace(" ", "_").str.replace("/", "_")

In [6]:
print(data['store_id'].nunique())
print(data['product_id'].nunique())

5
20

In [7]:
data['date'] = pd.to_datetime(data['date'])

In [8]:
data.isnull().sum()

date                  0
store_id              0
product_id            0
category              0
region                0
inventory_level       0
units_sold            0
units_ordered         0
demand_forecast       0
price                 0
discount              0
weather_condition     0
holiday_promotion     0
competitor_pricing    0
seasonality           0
dtype: int64

In [9]:
data['units_sold'] = data['units_sold'].fillna(data['units_sold'].mean())
data['price'] = data['price'].fillna(data['price'].mean())

In [10]:
data['weather_condition'] = data['weather_condition'].fillna("Unknown")

In [11]:
data = data.drop_duplicates()

In [12]:
data['day'] = data['date'].dt.day
data['month'] = data['date'].dt.month
data['year'] = data['date'].dt.year
data['day_of_week'] = data['date'].dt.dayofweek

In [13]:
data = pd.get_dummies(data, columns=[
    'category',
    'region',
    'weather_condition',
    'seasonality'
], drop_first=True)

In [14]:
print(data['holiday_promotion'].unique())

[0 1]

In [15]:
data['holiday_promotion'] = data['holiday_promotion'].replace({0:'No',1:'Yes'})

In [16]:
print(data['holiday_promotion'].unique())

['No' 'Yes']

In [17]:
data.head()

,date,store_id,product_id,inventory_level,units_sold,units_ordered,demand_forecast,price,discount,holiday_promotion,...,category_Toys,region_North,region_South,region_West,weather_condition_Rainy,weather_condition_Snowy,weather_condition_Sunny,seasonality_Spring,seasonality_Summer,seasonality_Winter
0,2022-01-01,S001,P0001,231,127,55,135.47,33.50,20,No,...,False,True,False,False,True,False,False,False,False,False
1,2022-01-01,S001,P0002,204,150,66,144.04,63.01,20,No,...,True,False,True,False,False,False,True,False,False,False
2,2022-01-01,S001,P0003,102,65,51,74.02,27.99,10,Yes,...,True,False,False,True,False,False,True,False,True,False
3,2022-01-01,S001,P0004,469,61,164,62.18,32.72,10,Yes,...,True,True,False,False,False,False,False,False,False,False
4,2022-01-01,S001,P0005,166,14,135,9.26,73.64,0,No,...,False,False,False,False,False,False,True,False,True,False

In [18]:
X = data.drop(['units_sold', 'date'], axis=1)
y = data['units_sold']

In [19]:
X = X.select_dtypes(include=['int64', 'float64'])

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [21]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=100,
    max_depth=10,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestRegressor(max_depth=10, random_state=42)

In [22]:
y_pred = model.predict(X_test)

In [23]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, y_pred)
print("MAE:", mae)

MAE: 7.159338771308636

In [24]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print("R2 Score:", r2)

R2 Score: 0.9940484999386272

In [26]:
print("Train Score:", model.score(X_train, y_train))
print("Test Score:", model.score(X_test, y_test))

Train Score: 0.9947590285668427
Test Score: 0.9940484999386272